### ISSUE TITLE
Season / Episode

### ISSUE THREAD

**Issue by MikeeI** [dewey/zdf-to-plex#1]
Found your project and it was helpful to see that there is a complete json for all, my solution is based on search and is lacking season and episode support. It helped me to upgrade my solution. 

BUT be careful, the season and episode information is not correct in some cases like inspector barnaby.

In the json an episode is stated to be season 1, episode 1. In reality it is season 23, episode 1. 
Its kind of random.

Just for information.

**Comment by dewey** [comment]
Glad it was useful, thanks for letting me know! Unfortunately their data quality is pretty bad in general. This also affects movies being listed as shows etc.

**Comment by MikeeI** [comment]
I used „https://api.zdf.de/search/documents/zdf/serien/inspector-barnaby/?sortOrder=desc&sortBy=date&hasVideo=true&contentTypes=episode“ 

```
         $item_target = $item["http://zdf.de/rels/target"];
         $item_programmed = $item_target["programmeItem"][0];
         $item_subtarget = $item_programmed["http://zdf.de/rels/target"];
         $item_season = $item_subtarget["http://zdf.de/rels/cmdm/season"];
         $episodeNumber = $item_subtarget["episodeNumber"];
         $seasonNumber = $item_season["seasonNumber"];
         if ($episodeNumber < 10) {
             $episodeNumber = '0' . $episodeNumber;
         }
         if ($seasonNumber < 10) {
             $seasonNumber = '0' . $seasonNumber;
         }
         $episodeTitle = $item_target["teaserHeadline"];
         $episodeDescription = $item_target["teasertext"];
         $episodeURL = $item_target["http://zdf.de/rels/sharing-url"];
         $episodeID = $item_target["id"];
```
